version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    environment: 
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - published: ${PGPORT_LOCAL}
        target: ${PGPORT_DOCKER}
